# to generate assembler listing with LTO, add to LDFLAGS: -Wa,-adhln=$@.listing,--listing-rhs-width=200
# for better annotations add -dA -dP
# to generate assembler source with LTO, add to LDFLAGS: -save-temps=cwd

OS := $(shell uname)

subdirs := $(wildcard */) $(wildcard src/*/) $(wildcard src/*/*/)
VPATH = $(subdirs)
SOURCE_DIR = src
BUILD_DIR = build/os4/obj
BUNDLE_DIR = bundle
CATALOG_DIR = $(BUNDLE_DIR)/AmigaGPT/catalogs
CATALOG_DEFINITION = $(CATALOG_DIR)/amigagpt.cd
catalog_subdirs := $(wildcard $(CATALOG_DIR)/*/)
catalog_translations := $(wildcard $(addsuffix *.ct,$(catalog_subdirs)))
temp_catalog_translations := $(addprefix $(BUILD_DIR)/,$(notdir $(catalog_translations)))
catalogs := $(patsubst %.ct,%.catalog,$(catalog_translations))
cpp_sources := $(wildcard *.cpp) $(wildcard $(addsuffix *.cpp,$(subdirs)))
cpp_objects := $(addprefix $(BUILD_DIR)/,$(patsubst %.cpp,%.o,$(notdir $(cpp_sources))))
c_sources := $(wildcard *.c) $(wildcard $(addsuffix *.c,$(subdirs)))
c_sources := $(filter-out $(SOURCE_DIR)/test/%, $(c_sources))
c_objects := $(addprefix $(BUILD_DIR)/,$(patsubst %.c,%.o,$(notdir $(c_sources))))
s_sources := $(wildcard *.s) $(wildcard $(addsuffix *.s,$(subdirs)))
s_objects := $(addprefix $(BUILD_DIR)/,$(patsubst %.s,%.o,$(notdir $(s_sources))))
vasm_sources := $(wildcard *.asm) $(wildcard $(addsuffix *.asm, $(subdirs)))
vasm_objects := $(addprefix $(BUILD_DIR)/, $(patsubst %.asm,%.o,$(notdir $(vasm_sources))))
objects := $(cpp_objects) $(c_objects) $(s_objects) $(vasm_objects)

AUTOGEN_FILE = $(SOURCE_DIR)/version.h
AUTOGEN_NEXT = $(shell expr $$(awk '/#define BUILD_NUMBER/' $(AUTOGEN_FILE) | tr -cd "[0-9]") + 1)

GIT_BRANCH = $(shell git rev-parse --abbrev-ref HEAD)
GIT_COMMIT = $(shell git rev-parse HEAD)
GIT_TIMESTAMP = $(shell git log -1 --format=%cd --date=format:"%Y-%m-%d~%H:%M:%S")

# https://stackoverflow.com/questions/4036191/sources-from-subdirectories-in-makefile/4038459
# http://www.microhowto.info/howto/automatically_generate_makefile_dependencies.html


PROGRAM_NAME = AmigaGPT_OS4
EXECUTABLE_DIR = out
EXECUTABLE_OUT = $(EXECUTABLE_DIR)/$(PROGRAM_NAME)
CC = ppc-amigaos-gcc

SDKLIBDIR = /opt/amiga/ppc-amigaos/SDK/lib
LIBDIR = /opt/amiga/ppc-amigaos/lib
SDKDIR = /opt/amiga/ppc-amigaos/SDK/include/include_h
NETINCDIR = /opt/amiga/ppc-amigaos/SDK/include/netinclude
INCDIR = /opt/amiga/ppc-amigaos/include

ifeq ($(OS),Darwin)
	SED = sed -i "" 
else
	SED = sed -i
endif

CCFLAGS = -MP -MMD -Wextra -Wno-unused-function -Wno-discarded-qualifiers -I$(INCDIR) -Wno-int-conversion -Wno-volatile-register-var -fomit-frame-pointer -fno-tree-loop-distribution -fno-exceptions -D__AMIGAOS4__ -D__amigaos4__ -D__USE_INLINE__ -DHAVE_VASPRINTF -DPROGRAM_NAME=\"$(PROGRAM_NAME)\" -DGIT_BRANCH=\"$(GIT_BRANCH)\" -DGIT_COMMIT=\"$(GIT_COMMIT)\" -DGIT_TIMESTAMP=\"$(GIT_TIMESTAMP)\"
ifeq ($(DEBUG),1)
	CCFLAGS += -DPROGDIR=\"OUT:\" -DDEBUG -g -O1
else
	CCFLAGS += -DPROGDIR=\"PROGDIR:\" -Ofast
endif
CPPFLAGS= $(CCFLAGS) -fno-rtti -fcoroutines -fno-use-cxa-atexit
ASFLAGS = -Wa,-g,--register-prefix-optional,-I$(SDKDIR),-I$(NETINCDIR),-I$(INCDIR),-D
LDFLAGS =  -Wl,-Map=$(EXECUTABLE_OUT).map,-L$(LIBDIR),-L$(SDKLIBDIR),-lm,-lamisslstubs,-ljson-c,-lauto
VASMFLAGS = -Fhunk -opt-fconst -nowarn=62 -dwarf=3 -quiet -x -I. -D__AMIGAOS4__ -DPROGRAM_NAME=\"$(PROGRAM_NAME)\" -I$(NETINCDIR) -I$(SDKDIR) -I$(INCDIR)

.PHONY: all clean copy_bundle_files

all: $(EXECUTABLE_OUT) copy_bundle_files 

clean:
	$(info Cleaning...)
	$(RM) $(SOURCE_DIR)/amigagpt_cat.*
	$(RM) $(catalogs)
	$(RM) -dr $(BUILD_DIR)

$(SOURCE_DIR)/amigagpt_cat.h: $(CATALOG_DEFINITION)
	$(info Generating catalog header)
	@$(RM) $@
	flexcat $< $@=C_h.sd

$(SOURCE_DIR)/amigagpt_cat.c: $(CATALOG_DEFINITION)
	$(info Generating catalog source)
	@$(RM) $@
	flexcat $< $@=C_c.sd

$(BUILD_DIR):
	@$(info Creating directory $@)
	mkdir -p $@

$(EXECUTABLE_DIR):
	@$(info Creating directory $@)
	mkdir -p $@

$(EXECUTABLE_OUT): $(EXECUTABLE_DIR) $(BUILD_DIR) $(catalogs) $(objects)
	$(info Linking $(PROGRAM_NAME))
	@$(RM) $@
	$(CC) $(CCFLAGS) $(LDFLAGS) $(objects) -o $@ $(LDFLAGS) 

-include $(objects:.o=.d)

$(temp_catalog_translations): $(catalog_translations) $(CATALOG_DEFINITION)
	$(info Copying catalog translations)
	$(RM) $@
# Allow it to fail the first time as the file may receive automatic adjustments
	-@flexcat $(CATALOG_DEFINITION) $< NEWCTFILE $<
	flexcat $(CATALOG_DEFINITION) $< NEWCTFILE $<
	@cp $< $@

$(catalogs): %.catalog : %.ct | $(SOURCE_DIR)/amigagpt_cat.h $(SOURCE_DIR)/amigagpt_cat.c $(temp_catalog_translations)
	$(info Compiling catalogs $<)
	$(RM) $@
	flexcat $(CATALOG_DEFINITION) $< CATALOG $@

$(cpp_objects): $(BUILD_DIR)/%.o : %.cpp | $(BUILD_DIR)/%.dir
	$(info Compiling $<)
	$(CC) $(CPPFLAGS) -c -o $@ $(CURDIR)/$<

$(c_objects): $(BUILD_DIR)/%.o : %.c
	$(info Compiling $<)
	@$(SED) 's|#define BUILD_NUMBER ".*"|#define BUILD_NUMBER "$(AUTOGEN_NEXT)"|' $(AUTOGEN_FILE)
	$(CC) $(CCFLAGS) -c -o $@ $(CURDIR)/$<

$(s_objects): $(BUILD_DIR)/%.o : %.s
	$(info Assembling $<)
	$(CC) $(CCFLAGS) $(ASFLAGS) -c -o $@ $(CURDIR)/$<

$(vasm_objects): $(BUILD_DIR)/%.o : %.asm
	$(info Assembling $<)
	$(VASM) $(VASMFLAGS) -o $@ $(CURDIR)/$<

copy_bundle_files:
	$(info Copying bundle files...)
	cp assets/AmigaGPT_OS4.info $(BUNDLE_DIR)/AmigaGPT/$(PROGRAM_NAME).info
	cp -R bundle/AmigaGPT/* out/
	