# to generate assembler listing with LTO, add to LDFLAGS: -Wa,-adhln=$@.listing,--listing-rhs-width=200
# for better annotations add -dA -dP
# to generate assembler source with LTO, add to LDFLAGS: -save-temps=cwd

OS := $(shell uname)

subdirs := $(wildcard */) $(wildcard src/*/) $(wildcard src/*/*/)
VPATH = $(subdirs)
BUILD_DIR := build/os4/obj/
cpp_sources := $(wildcard *.cpp) $(wildcard $(addsuffix *.cpp,$(subdirs)))
cpp_objects := $(addprefix $(BUILD_DIR),$(patsubst %.cpp,%.o,$(notdir $(cpp_sources))))
c_sources := $(wildcard *.c) $(wildcard $(addsuffix *.c,$(subdirs)))
c_objects := $(addprefix $(BUILD_DIR),$(patsubst %.c,%.o,$(notdir $(c_sources))))
s_sources := $(wildcard *.s) $(wildcard $(addsuffix *.s,$(subdirs)))
s_objects := $(addprefix $(BUILD_DIR),$(patsubst %.s,%.o,$(notdir $(s_sources))))
vasm_sources := $(wildcard *.asm) $(wildcard $(addsuffix *.asm, $(subdirs)))
vasm_objects := $(addprefix $(BUILD_DIR), $(patsubst %.asm,%.o,$(notdir $(vasm_sources))))
objects := $(cpp_objects) $(c_objects) $(s_objects) $(vasm_objects)

AUTOGEN_FILE := src/version.h
AUTOGEN_NEXT := $(shell expr $$(awk '/#define BUILD_NUMBER/' $(AUTOGEN_FILE) | tr -cd "[0-9]") + 1)


# https://stackoverflow.com/questions/4036191/sources-from-subdirectories-in-makefile/4038459
# http://www.microhowto.info/howto/automatically_generate_makefile_dependencies.html


PROGRAM_NAME = AmigaGPT
EXECUTABLE_OUT = out/$(PROGRAM_NAME)
PACKAGE_OUT = out/$(PROGRAM_NAME)OS4.lha
CC = ppc-amigaos-gcc

LIBDIR = /tools/ppc-amigaos/SDK/lib
SDKDIR = /tools/ppc-amigaos/SDK/include/include_h
NETINCDIR = /tools/ppc-amigaos/SDK/include/netinclude

ifeq ($(OS),Darwin)
	SED = sed -i "" 
else
	SED = sed -i
endif

CCFLAGS = -gdwarf-2 -MP -MMD -Ofast -Wextra -Wno-unused-function -Wno-discarded-qualifiers -Wno-int-conversion -Wno-volatile-register-var -fomit-frame-pointer -fno-tree-loop-distribution -flto -fwhole-program -fno-exceptions -L$(LIBDIR) -lm -lamisslstubs -D__AMIGAOS4__ -D__USE_INLINE__ -DHAVE_VASPRINTF -DPROGRAM_NAME=\"$(PROGRAM_NAME)\"
CPPFLAGS= $(CCFLAGS) -fno-rtti -fcoroutines -fno-use-cxa-atexit
ASFLAGS = -Wa,-g,--register-prefix-optional,-I$(SDKDIR),-I$(NETINCDIR),-D
LDFLAGS =  -Wl,-Map=$(EXECUTABLE_OUT).map
VASMFLAGS = -Fhunk -opt-fconst -nowarn=62 -dwarf=3 -quiet -x -I. -D__AMIGAOS4__ -DPROGRAM_NAME=\"$(PROGRAM_NAME)\" -I$(NETINCDIR) -I$(SDKDIR)

.PHONY: all clean copy_bundle_files package

all: $(EXECUTABLE_OUT) copy_bundle_files $(PACKAGE_OUT)

$(BUILD_DIR):
	@$(info Creating directory $@)
	@mkdir -p $@

$(EXECUTABLE_OUT): $(objects)
	$(info Linking $(PROGRAM_NAME))
	$(CC) $(CCFLAGS) $(LDFLAGS) $(objects) -o $@

clean:
	$(info Cleaning...)
	@$(RM) $(BUILD_DIR)*

-include $(objects:.o=.d)

$(cpp_objects) : build/os4/obj/%.o : %.cpp | build/os4/obj/%.dir
	$(info Compiling $<)
	$(CC) $(CPPFLAGS) -c -o $@ $(CURDIR)/$<

$(c_objects) : build/os4/obj/%.o : %.c | $(BUILD_DIR)
	$(info Compiling $<)
	$(SED) 's|#define BUILD_NUMBER ".*"|#define BUILD_NUMBER "$(AUTOGEN_NEXT)"|' $(AUTOGEN_FILE)
	$(CC) $(CCFLAGS) -c -o $@ $(CURDIR)/$<

$(s_objects): build/os4/obj/%.o : %.s |$(BUILD_DIR)
	$(info Assembling $<)
	$(CC) $(CCFLAGS) $(ASFLAGS) -c -o $@ $(CURDIR)/$<

$(vasm_objects): build/os4/obj/%.o : %.asm | $(BUILD_DIR)
	$(info Assembling $<)
	$(VASM) $(VASMFLAGS) -o $@ $(CURDIR)/$<

copy_bundle_files:
	$(info Copying bundle files...)
	cp assets/AmigaGPTOS4.info bundle/$(PROGRAM_NAME)/$(PROGRAM_NAME).info
	cp -R bundle/$(PROGRAM_NAME)/* out/
	
$(PACKAGE_OUT): $(EXECUTABLE_OUT)
	$(info Creating LHA package...)
	@rm -f $(PACKAGE_OUT)
	cp $(EXECUTABLE_OUT) bundle/$(PROGRAM_NAME)/
	cd bundle && lha a -v ../out/$(PROGRAM_NAME).lha $(PROGRAM_NAME) $(PROGRAM_NAME).info
	rm bundle/$(PROGRAM_NAME)/$(PROGRAM_NAME)
