/* AmigaGPT Translates the selected text in TextEdit to Norwegian */
OPTIONS RESULTS

ADDRESS 'TEXTEDIT.1'

'GETSELECTEDTEXT'

ADDRESS 'AMIGAGPT'

'SENDMESSAGE M=gpt-5-mini Translate the following into Norwegian: 'SELECTEDTEXT

TRANSLATEDTEXT = RESULT

ADDRESS 'TEXTEDIT.1'

'BACKSPACE'

'TEXT 'TRANSLATEDTEXT

EXIT
