#define OLD_SPEECH
// #define EMULATOR
#define TRANSLATION_BUFFER_LENGTH 1000
#define WIN_LEFT_EDGE 0
#define WIN_TOP_EDGE 0
#define WIN_WIDTH 640
#define WIN_MIN_WIDTH 640
#define WIN_HEIGHT 500
#define WIN_MIN_HEIGHT 500
#define BUTTON_GADGET_NUM 0
#define BUTTON_WIDTH 100
#define BUTTON_HEIGHT 30