#include <proto/dos.h>

enum MenuItemID {
    MENU_ITEM_NULL = 0L,
    MENU_ITEM_PROJECT,
    MENU_ITEM_PROJECT_ABOUT_AMIGAGPT,
    MENU_ITEM_PROJECT_ABOUT_MUI,
    MENU_ITEM_PROJECT_QUIT,
    MENU_ITEM_EDIT,
    MENU_ITEM_EDIT_CUT,
    MENU_ITEM_EDIT_COPY,
    MENU_ITEM_EDIT_PASTE,
    MENU_ITEM_EDIT_CLEAR,
    MENU_ITEM_EDIT_SELECT_ALL,
    MENU_ITEM_VIEW,
    MENU_ITEM_VIEW_MUI_SETTINGS,
    MENU_ITEM_VIEW_FIXED_WIDTH_FONTS,
    MENU_ITEM_CONNECTION,
    MENU_ITEM_CONNECTION_PROXY,
    MENU_ITEM_CONNECTION_PROXY_ENABLED,
    MENU_ITEM_CONNECTION_PROXY_SETTINGS,
    MENU_ITEM_SPEECH,
    MENU_ITEM_SPEECH_ENABLED,
    MENU_ITEM_SPEECH_SYSTEM,
    MENU_ITEM_SPEECH_ACCENT,
    MENU_ITEM_SPEECH_FLITE_VOICE,
    MENU_ITEM_SPEECH_OPENAI_VOICE,
    MENU_ITEM_SPEECH_OPENAI_VOICE_INSTRUCTIONS,
    MENU_ITEM_SPEECH_OPENAI_MODEL,
    MENU_ITEM_OPENAI,
    MENU_ITEM_OPENAI_API_KEY,
    MENU_ITEM_OPENAI_CHAT_SYSTEM,
    MENU_ITEM_OPENAI_CHAT_MODEL,
    MENU_ITEM_OPENAI_IMAGE_MODEL,
    MENU_ITEM_OPENAI_IMAGE_SIZE_DALL_E_2,
    MENU_ITEM_OPENAI_IMAGE_SIZE_DALL_E_3,
    MENU_ITEM_OPENAI_IMAGE_SIZE_GPT_IMAGE_1,
    MENU_ITEM_AREXX,
    MENU_ITEM_AREXX_AREXX_SHELL,
    MENU_ITEM_AREXX_IMPORT_SCRIPT,
    MENU_ITEM_AREXX_RUN_SCRIPT,
    MENU_ITEM_AREXX_SCRIPT,
    MENU_ITEM_HELP,
    MENU_ITEM_HELP_OPEN_DOCUMENTATION
};

extern Object *menuStrip;

void createMenu();

void addMenuActions();
