#include <proto/dos.h>

enum MenuItemID {
    MENU_ITEM_NULL = 0L,
    MENU_ITEM_PROJECT,
    MENU_ITEM_PROJECT_PRINT,
    MENU_ITEM_PROJECT_ABOUT_AMIGAGPT,
    MENU_ITEM_PROJECT_ABOUT_MUI,
    MENU_ITEM_PROJECT_QUIT,
    MENU_ITEM_EDIT,
    MENU_ITEM_EDIT_CUT,
    MENU_ITEM_EDIT_COPY,
    MENU_ITEM_EDIT_PASTE,
    MENU_ITEM_EDIT_CLEAR,
    MENU_ITEM_EDIT_SELECT_ALL,
#ifdef __MORPHOS__
    MENU_ITEM_EDIT_FIND,
    MENU_ITEM_EDIT_FIND_NEXT,
#endif
    MENU_ITEM_VIEW,
    MENU_ITEM_VIEW_MUI_SETTINGS,
    MENU_ITEM_VIEW_CLEAR_MUI_SETTINGS,
    MENU_ITEM_VIEW_FIXED_WIDTH_FONTS,
    MENU_ITEM_VIEW_MARKDOWN_FORMATTING,
    MENU_ITEM_VIEW_CHAT_LINE_WRAP,
    MENU_ITEM_VIEW_CHAT_FONT_LARGER,
    MENU_ITEM_VIEW_CHAT_FONT_SMALLER,
    MENU_ITEM_VIEW_USER_TEXT_ALIGNMENT,
    MENU_ITEM_VIEW_USER_TEXT_ALIGNMENT_LEFT,
    MENU_ITEM_VIEW_USER_TEXT_ALIGNMENT_CENTER,
    MENU_ITEM_VIEW_USER_TEXT_ALIGNMENT_RIGHT,
    MENU_ITEM_VIEW_ASSISTANT_TEXT_ALIGNMENT,
    MENU_ITEM_VIEW_ASSISTANT_TEXT_ALIGNMENT_LEFT,
    MENU_ITEM_VIEW_ASSISTANT_TEXT_ALIGNMENT_CENTER,
    MENU_ITEM_VIEW_ASSISTANT_TEXT_ALIGNMENT_RIGHT,
    MENU_ITEM_VIEW_CODEBLOCKS,
    MENU_ITEM_VIEW_EXPORT_CHAT_RAW,
    MENU_ITEM_CONNECTION,
    MENU_ITEM_CONNECTION_PROXY,
    MENU_ITEM_CONNECTION_PROXY_ENABLED,
    MENU_ITEM_CONNECTION_PROXY_SETTINGS,
    MENU_ITEM_SPEECH,
    MENU_ITEM_SPEECH_ENABLED,
    MENU_ITEM_SPEECH_PROVIDER_SETTINGS,
    MENU_ITEM_CHAT,
    MENU_ITEM_CHAT_PROVIDER_SETTINGS,
    MENU_ITEM_IMAGE,
    MENU_ITEM_IMAGE_PROVIDER_SETTINGS,
    MENU_ITEM_AREXX,
    MENU_ITEM_AREXX_AREXX_SHELL,
    MENU_ITEM_AREXX_IMPORT_SCRIPT,
    MENU_ITEM_AREXX_RUN_SCRIPT,
    MENU_ITEM_AREXX_SCRIPT,
    MENU_ITEM_HELP,
    MENU_ITEM_HELP_OPEN_DOCUMENTATION
};

extern Object *menuStrip;

void createMenu();

void addMenuActions();

#ifdef __MORPHOS__
/** Enable "View code blocks…" when the current chat has ``` blocks. */
void refreshViewCodeBlocksMenuState(void);
/** Gray out chat font +/- at min/max size (8–24 pt). */
void refreshChatFontMenuState(void);
#endif

/**
 * @brief Enable or disable the Edit menu items depending on whether one of the
 * input text editors currently holds the keyboard focus
 */
void updateEditMenuItemsEnabled();
