name: Build and package the app for all platforms

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build and package
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build and package
        run: |
          ./package.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AmigaGPT
          path: out/AmigaGPT.lha
